<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>pt.unl.fct.di.novasys.iot</groupId>
	<artifactId>pi4j-iot-device-library-j17</artifactId>
	<version>0.0.16</version>
	<name>Pi4J IoT Device Library</name>

	<developers>
		<developer>
			<name>João Brilha</name>
			<email>j.brilha@campus.fct.unl.pt</email>
			<url></url>
		</developer>
		<developer>
			<name>João Leitão</name>
			<email>jc.leitao@fct.unl.pt</email>
			<url>https://asc.di.fct.unl.pt/~jleitao</url>
		</developer>
	</developers>


	<description>This is a IoT Device Library written in Java that was built 
	on top of the Pi4J library. It includes multiple types of devices and is 
	fully compatible with Raspberry Pis 4 and 5.</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<repositories>
		<repository>
			<id>novasys-mvn</id>
			<url>https://novasys.di.fct.unl.pt/packages/mvn</url>
		</repository>
	</repositories>


	<dependencies>
		<dependency>
			<groupId>com.github.yafna.raspberry</groupId>
			<artifactId>grovepi-pi4j-j17</artifactId>
			<version>0.5.0</version>
		</dependency>

		<dependency>
			<groupId>com.pi4j</groupId>
			<artifactId>pi4j-components-j17</artifactId>
			<version>0.0.5</version>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>novasys-deploy</id>
			<activation>
				<property>
					<name>novasys</name>
				</property>
			</activation>
			<distributionManagement>
				<repository>
					<id>novasys-deploy</id>
					<url>${NOVASYS_PACKAGE_MVN_PATH}</url>
				</repository>
				<snapshotRepository>
					<id>novasys-deploy</id>
					<url>${NOVASYS_PACKAGE_MVN_PATH}</url>
				</snapshotRepository>
			</distributionManagement>
		</profile>
		<profile>
			<id>codelab-deploy</id>
			<activation>
				<property>
					<name>codelab</name>
				</property>
			</activation>
			<distributionManagement>
				<repository>
					<id>codelab-deploy</id>
					<url>
						${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven</url>
				</repository>
				<snapshotRepository>
					<id>codelab-deploy</id>
					<url>
						${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven</url>
				</snapshotRepository>
			</distributionManagement>
		</profile>
	</profiles>

	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<extensions>
			<!-- Enabling the use of SSH -->
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh-external</artifactId>
				<version>1.0-beta-6</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.12.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.3.1</version>
				<executions>
					<execution>
						<id>generate-sources</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.6.3</version>
				<configuration>
					<source>17</source>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>jar</goal>
							<goal>javadoc</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
